
# numpy Introduction
Author: Julian Lißner<br>
For questions and feedback please write a mail to: [lissner@mib.uni-stuttgart.de](mailto:lissner@mib.uni-stuttgart.de)


## numpy...
- is at the top of almost every script
- brings matrix operations to python
- comes with additional functionalities/subpackages

In [1]:
import numpy as np

## Creating arrays

In [12]:
x = np.array( [ 2, 5,1] )
A = np.array( [ [2,5 ,2], [ 1, 4, 3] ] )
I = np.eye( 3) 
B = np.random.rand( 6, 12)
II = np.ones( (2,3 ) )
w = np.arange( 12* 6)
U = np.reshape( w, (12, 6) )

G = np.zeros( (4, 3) )
#print(G)
#print(G.shape[0] )
for i in range( 3):
    G[ :,i] = np.arange( G.shape[0] )**i 
    #print(G)
print("x = ",x)
print("A = ",A)
print("A.T = ",A.T)
print("I = ",I)
print("II = ",II)
print("w = ",w)
print("B = ",B)
print("U = ",U)

x =  [2 5 1]
A =  [[2 5 2]
 [1 4 3]]
A.T =  [[2 1]
 [5 4]
 [2 3]]
I =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
II =  [[1. 1. 1.]
 [1. 1. 1.]]
w =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71]
B =  [[0.7642962  0.72420473 0.0505443  0.3434011  0.49923602 0.8264337
  0.6735265  0.79052027 0.34225518 0.90444451 0.43242669 0.23156176]
 [0.33433201 0.34290125 0.06793009 0.45252259 0.31398802 0.86888686
  0.57798587 0.31929285 0.31184359 0.50297337 0.18428207 0.4829115 ]
 [0.14653438 0.29157605 0.47093966 0.3924841  0.51745691 0.1142705
  0.23428983 0.12276462 0.62964241 0.35750141 0.06210851 0.771991  ]
 [0.96984639 0.19013572 0.25953095 0.41345897 0.39127429 0.15699914
  0.30196991 0.67932448 0.10103357 0.93074785 0.34393931 0.59858511]
 [0.50860054 0.47503655 0.85389645 0.14540447 0.1807719  0.94763339
  0.91094949 0.79

## Accessing elements

- element can be accessed by index brackets `[ ]` <br>
$\quad$ with indices: `array[i, j]` <br>
$\quad$ or slices: `array[ start:stop:increment, :stop]`<br>
$\quad$ or combinations of those


In [11]:
A = np.arange( 4*3).reshape( 4, 3)

print("A = ",A)
print( 'two integer', A[0, 0] )
print( 'list and integer', A[ [0,1], -1 ] )
print( 'one integer at the first index', A[ 3] )
print( 'one integer at the last index', A[ ..., 2] )
print( 'only list\n', A[ [1, 2] ])
print( 'only tuple\n', A[ (-1, -2) ])
print( 'type of a slice', type( A[...,4:] ) )
print( 'type of a slice', A[...,2:]  )
print( 'slices\n', A[::2, 3::-1])

A =  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
two integer 0
list and integer [2 5]
one integer at the first index [ 9 10 11]
one integer at the last index [ 2  5  8 11]
only list
 [[3 4 5]
 [6 7 8]]
only tuple
 10
type of a slice <class 'numpy.ndarray'>
type of a slice [[ 2]
 [ 5]
 [ 8]
 [11]]
slices
 [[2 1 0]
 [8 7 6]]


------
------

## Array operations

#### Matrix multiplication
- numpy adds the _@_ operator
- np.einsum, np.dot, np.matmul, ... <br>
$
C_{ik} = \sum\limits_{j=0}^{n-1} b_{ij}u_{jk} \, \widehat= \,  B_{ij}\, U_{jk}
$<br>
$C=$ components $\hat=$ Einstein notation

In [13]:
C = np.matmul( B, U)
C = B @ U #matrix multiplication
b = np.einsum( 'ij, ki -> jk', U, B ) # U.T @ B.T
assert ( B @ U == np.matmul( B, U)).all()
print(b)

[[242.93613    143.61444321 244.56002585 197.01163793 201.02527556
  236.00097027]
 [249.34718308 149.04081113 251.36746936 203.4796473  205.92301491
  242.45991564]
 [255.75823616 154.46717905 258.17491287 209.94765667 210.82075427
  248.918861  ]
 [262.16928924 159.89354697 264.98235638 216.41566605 215.71849363
  255.37780637]
 [268.58034233 165.3199149  271.78979989 222.88367542 220.61623298
  261.83675173]
 [274.99139541 170.74628282 278.5972434  229.3516848  225.51397234
  268.2956971 ]]


In [18]:
print( 'A.shape :',  A.shape)
print( 'x.shape :',  x.shape)

if (x == x.T).all():
    print( '1d-arrays: x == x.T') 
b = A @ x
c = x @ A.T
#d = A.T @ x.T
print( 'are b and c equal?', (b==c).all() )

A.shape : (4, 5)
x.shape : (5,)
1d-arrays: x == x.T
are b and c equal? True


- python operators ( +, -, ...) are __always__ element wise
- element operations are always applied to the last slot 

In [16]:
x = np.array( [ 3, 6, 9] ) 
y = x + 3
print( y)

[ 6  9 12]


In [17]:
x = np.arange( 5)
A = np.ones( ( 4,5)) 
print( 'x *0.2 :',  x *0.2)
print( 'A:\n',  A)
A = A * 2
print( 'A*2:\n',  A) 

x *0.2 : [0.  0.2 0.4 0.6 0.8]
A:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
A*2:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [21]:
print( 'x**2 :',  x**2)
print( 'x@ x :',  x@ x)
print( 'x* x :',  x* x)
print( 'A * A :',  A * A)

x**2 : [ 0  1  4  9 16]
x@ x : 30
x* x : [ 0  1  4  9 16]
A * A : [[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [22]:
print( 'A.shape :',  A.shape)
print( 'x.shape :',  x.shape)
print( 'A * x :',  A * x) 
print( 'x *A  :',  x *A ) 

A.shape : (4, 5)
x.shape : (5,)
A * x : [[0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]]
x *A  : [[0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]]


In [25]:
print( 'A.T * x :',  A.T * x) 

ValueError: operands could not be broadcast together with shapes (5,4) (5,) 

In [26]:
print( 'x * A.T  :',  x * A.T ) 

ValueError: operands could not be broadcast together with shapes (5,) (5,4) 

- A.shape == ( 10, 12), x.shape == (12,) $\to$ A\*x works
- A.shape == ( 10, 12, 5), x.shape == (12, 5) $\to$ A\*x works
- A.shape == ( 10, 12), x.shape == (10, 12) $\to$ A\*x works

----
---- 


## Array methods
- numpy arrays are objects
- recall lists, `object.method()`

In [27]:
print( 'numpy function:', np.sum( x), 'object function:', x.sum() )
y = w.reshape( 12, 6)
print( 'attribute shape:', w.shape )
print( y.shape, 'last index size:', y.shape[-1])
print()
#However
m = np.random.randn( 4)
print( 'm originally:\t', m)

s = m.sum()
print( 'm after sum:\t', m )
print( 'sum of m:\t', s )

z = m.sort()
print( 'm after sorting:', m)
print( 'new variable z:', z)

numpy function: 10 object function: 10
attribute shape: (72,)
(12, 6) last index size: 6

m originally:	 [ 0.25713046  1.59715491  2.32304986 -0.97838556]
m after sum:	 [ 0.25713046  1.59715491  2.32304986 -0.97838556]
sum of m:	 3.1989496776643556
m after sorting: [-0.97838556  0.25713046  1.59715491  2.32304986]
new variable z: None


$\to$ read `help()` documentation

In [13]:
#help( np.ndarray.sort)
#help( y.sort )

## numpy packages
- linalg, random, fft, doc
- lib, polynomial, testing, f2py, distutils

In [28]:
import numpy as np
import numpy.linalg as la_2
from numpy import linalg as la

if np.linalg.det is la.det and la.det is la_2.det:
    print( 'there are multiple ways to import subpackages ')

there are multiple ways to import subpackages 


In [29]:
_ = [print( x) for x in dir( np.linalg) if x[0] != '_']

LinAlgError
cholesky
cond
det
eig
eigh
eigvals
eigvalsh
inv
lapack_lite
linalg
lstsq
matrix_power
matrix_rank
multi_dot
norm
pinv
qr
slogdet
solve
svd
tensorinv
tensorsolve
test


In [30]:
help( np.linalg.det)

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matrices:
    
 

In [33]:
x = np.random.randn( 15, 41 )
C = np.random.rand( 20, 20)
s = np.linalg.det( C) 
f = np.fft.fft2( x)
L, V = np.linalg.eig( C)
U, S, V = np.linalg.svd( C)
F = np.linalg.inv( C)

In [34]:
print( U.shape, S.shape, V.shape)
C_hat = (U * S ) @ V

(20, 20) (20,) (20, 20)


In [35]:
if np.allclose( C, C_hat):
    print( 'array correctly reassembled')
else:
    print( 'array not correctly reassembled')

array correctly reassembled
