# Array flattening demo

Felix Fritzen (fritzen@simtech.uni-stuttgart.de)

Data Processing for Engineers and Scientists


## Reshaping a simple vector in `python`

In [1]:
import numpy as np

a = np.arange(1,25)
a2= a.reshape([12, 2])
a3= a.reshape([2,3,4])

print(a)
print(a2)
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## Reshaping the same vector in `MATLAB`
`a2 = reshape( 1:24, 12, 2)`<br>
`disp(a2)`

     1    13
     2    14
     3    15
     4    16
     5    17
     6    18
     7    19
     8    20
     9    21
    10    22
    11    23
    12    24

`a3 = reshape(a, 2,3,4)`<br>
`disp(reshape(a3(1,:,:),3,4))`<br>

     1     7    13    19
     3     9    15    21
     5    11    17    23

`disp(reshape(a3(2,:,:),3,4))`<br>

     2     8    14    20
     4    10    16    22
     6    12    18    24
     